### ISSUE TITLE
Increased latency with concurrent GPS + modem operation in nrf thingy91 due to switching multiplexing

### ISSUE THREAD

**Issue by govindsi** [NordicSemiconductor/asset-tracker-cloud-firmware-aws#275]
We are seeing issue with concurrent GPS + modem operation (increased latency)  in nrf thingy91 due to switching multiplexing.
It was mentioned in the following repo that future modem firmware will allow both modes to be active simultaneously.
Is the new modem firmware available with this feature?

**https://github.com/ExploratoryEngineering/nrf9160-gps/tree/master**
The nRF9160 shares a single radio for GPS and LTE, and the current modem firmware (0.7.0-29.alpha) only allows one to be active at a time. We therefore have to switch back and forth between these modes in order to collect GPS data and send it. This switching introduces a delay which we minimize by buffering position data and sending it in batches. **A future modem firmware will allow both modes to be active simultaneously, which will enable streaming of location data**.

**Comment by coderbyheart** [comment]
Hei Govind,

please ask question related to modem firmware in [{DevZone](https://devzone.nordicsemi.com/). Thank you!
